apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-deployment
  labels:
    app: healthcare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
      - name: healthcare-container
        image: faris7/healthcareproject:v3
        ports:
        - containerPort: 8082   # Change if your app runs on another port
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-k8ssvc
spec:
  type: NodePort
  selector:
    app: healthcare
  ports:
    - port: 8080          # Exposed service port
      targetPort: 8082    # Match containerPort (your app port)
      nodePort: 31354     # Or leave it out to auto-assign
