apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-deployment
  labels:
    app: healthcare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
      - name: healthcare-container
        image: faris7/healthcareproject:v3
        ports:
        - containerPort: 8082          # <--- updated port
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-service
spec:
  selector:
    app: healthcare
  ports:
  - protocol: TCP
    port: 80                          # Exposed service port
    targetPort: 8082                  # <--- updated targetPort to match container
  type: LoadBalancer                  # Exposes it externally
